id: "code_assistant"
name: "Code Assistant"
description: "Specialized agent for programming assistance and technical queries"
version: "1.0.0"
enabled: true
agent_type: "code_assistant_agent"
capabilities:
  - "code_explanation"
  - "code_generation"
  - "debugging"

model_config:
  provider: "granite"
  model_type: "instruct"
  model_name: "granite-3-1-8b-instruct-w4a16"
  max_tokens: 2048
  temperature: 0.2

prompts:
  system:
    id: "assistants.code_assistant"
    description: "System prompt for code assistance functionality"

tools: []
